name: 'first pipeline'
on:
  push:
    branches:
          - "master"

job:
  testing:
      name: "test pip line"
      runs_on: "ubuntu"
      steps:
          name: "say hello"
          run: echo "hello world"