name: 'first pipeline'
on:
  push:
    branches:
      - "master"

jobs:
  testing:
    name: "test pip line"
    runs_on: ubuntu-latest
    steps:
      - name: "say hello"
        run: echo "hello world"